version: '3'
volumes:
    mongodb-data:
        name: mongodb-data

networks:
    mongodb_network:
        name: mongodb_network


services:
    mongodb:
        image: 2d38962b1e5e
        restart: unless-stopped
        container_name: sangwoo-mongo
        ports:
            - "27017:27017"
        environment:
          MONGO_INITDB_ROOT_USERNAME: sangwoo
          MONGO_INITDB_ROOT_PASSWORD: password
        volumes:
            - mongodb-data:/data/db
        networks:
            - mongodb_network
    